### ISSUE TITLE
别名服务器失联，请暂时使用本地别名库

### ISSUE THREAD

**Issue by Yuri-YuzuChaN** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#15]

**Comment by Bejukoro** [comment]
别名服务器连接超时导致插件报错 Bot无法启动
日志如下
```
03-17 16:36:25 [INFO] nonebot_plugin_maimaidx | 正在获取maimai所有曲目别名信息
03-17 16:36:56 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
    raise exc
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
    data = await self._network_stream.read(
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Lugh/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 153, in _lifespan_manager
    await self._lifespan.startup()
  File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot/internal/driver/_lifespan.py", line 41, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot/internal/driver/_lifespan.py", line 35, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot_plugin_maimaidx/__init__.py", line 132, in get_music
    await mai.get_music_alias()
  File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot_plugin_maimaidx/libraries/maimaidx_music.py", line 402, in get_music_alias
    self.total_alias_list = await get_music_alias_list()
  File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot_plugin_maimaidx/libraries/maimaidx_music.py", line 338, in get_music_alias_list
    alias_data = await maiApi.get_alias()
  File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot_plugin_maimaidx/libraries/maimaidx_api_data.py", line 98, in get_alias
    return await self._request('GET', self.MaiAliasAPI + '/maimaidxalias')
  File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot_plugin_maimaidx/libraries/maimaidx_api_data.py", line 24, in _request
    res = await session.request(method, url, **kwargs)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

03-17 16:36:56 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by Yuri-YuzuChaN** [comment]
> 别名服务器连接超时导致插件报错 Bot无法启动 日志如下
> 
> ```
> 03-17 16:36:25 [INFO] nonebot_plugin_maimaidx | 正在获取maimai所有曲目别名信息
> 03-17 16:36:56 [ERROR] uvicorn | Traceback (most recent call last):
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
>     yield
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
>     resp = await self._pool.handle_async_request(req)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
>     raise exc from None
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
>     response = await connection.handle_async_request(
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
>     return await self._connection.handle_async_request(request)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
>     raise exc
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
>     ) = await self._receive_response_headers(**kwargs)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
>     event = await self._receive_event(timeout=timeout)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
>     data = await self._network_stream.read(
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 31, in read
>     with map_exceptions(exc_map):
>   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc) from exc
> httpcore.ReadTimeout
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
>     async with self.lifespan_context(app) as maybe_state:
>   File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
>     return await anext(self.gen)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 153, in _lifespan_manager
>     await self._lifespan.startup()
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot/internal/driver/_lifespan.py", line 41, in startup
>     await self._run_lifespan_func(self._startup_funcs)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot/internal/driver/_lifespan.py", line 35, in _run_lifespan_func
>     await cast(ASYNC_LIFESPAN_FUNC, func)()
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot_plugin_maimaidx/__init__.py", line 132, in get_music
>     await mai.get_music_alias()
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot_plugin_maimaidx/libraries/maimaidx_music.py", line 402, in get_music_alias
>     self.total_alias_list = await get_music_alias_list()
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot_plugin_maimaidx/libraries/maimaidx_music.py", line 338, in get_music_alias_list
>     alias_data = await maiApi.get_alias()
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot_plugin_maimaidx/libraries/maimaidx_api_data.py", line 98, in get_alias
>     return await self._request('GET', self.MaiAliasAPI + '/maimaidxalias')
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/nonebot_plugin_maimaidx/libraries/maimaidx_api_data.py", line 24, in _request
>     res = await session.request(method, url, **kwargs)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
>     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
>     response = await self._send_handling_auth(
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
>     response = await self._send_handling_redirects(
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
>     response = await self._send_single_request(request)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
>     response = await transport.handle_async_request(request)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
>     with map_httpcore_exceptions():
>   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/root/Lugh/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.ReadTimeout
> 
> 03-17 16:36:56 [ERROR] uvicorn | Application startup failed. Exiting.
> ```

别名服务器已恢复
