### ISSUE TITLE
输入指令   12完成表   时发生错误 

### ISSUE THREAD

**Issue by TsukimoriRin** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#31]
06-24 18:02:53 [ERROR] nonebot_plugin_maimaidx | Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\bot\xxxx\.venv\lib\site-packages\nonebot_plugin_maimaidx\libraries\maimaidx_music_info.py", line 262, in draw_rating_table
    im = Image.open(bg).convert('RGBA')
  File "C:\Users\xxxx\Desktop\bot\xxxx\.venv\lib\site-packages\PIL\Image.py", line 3277, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxx\\Desktop\\bot\\xxxx\static\\mai\\rating\\11.png'

输入指令   12完成表   时发生错误 请问大大该怎么解决
![QQ截图20240624181039](https://github.com/Yuri-YuzuChaN/nonebot-plugin-maimaidx/assets/173679896/79de55a5-4f52-4f95-8010-ae99cce50de1)

**Comment by Yuri-YuzuChaN** [comment]
#28

**Comment by TsukimoriRin** [comment]
感谢！！
