### ISSUE TITLE
别名库炸了？

### ISSUE THREAD

**Issue by zeronsama** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#34]
检查发现 <https://api.yuzuchan.moe/maimaidx> 似乎没有返回正确值 

```txt
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/python3/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 165, in _lifespan_manager
    await self._lifespan.startup()
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/drivers/_lifespan.py", line 35, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "/usr/local/python3/lib/python3.9/site-packages/nonebot/drivers/_lifespan.py", line 29, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "/home/www/arsbot/src/thirdparty/nonebot_plugin_maimaidx/__init__.py", line 32, in get_music
    await mai.get_music_alias()
  File "/home/www/arsbot/src/thirdparty/nonebot_plugin_maimaidx/libraries/maimaidx_music.py", line 339, in get_music_alias
    self.total_alias_list = await get_music_alias_list()
  File "/home/www/arsbot/src/thirdparty/nonebot_plugin_maimaidx/libraries/maimaidx_music.py", line 279, in get_music_alias_list
    alias_data = await maiApi.get_alias()
  File "/home/www/arsbot/src/thirdparty/nonebot_plugin_maimaidx/libraries/maimaidx_api_data.py", line 124, in get_alias
    return await self._request('GET', self.MaiAliasAPI + '/maimaidxalias')
  File "/home/www/arsbot/src/thirdparty/nonebot_plugin_maimaidx/libraries/maimaidx_api_data.py", line 29, in _request
    res = await session.request(method, url, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/python3/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
```

**Comment by Yuri-YuzuChaN** [comment]
别名库一切正常，检查自身网络情况

**Comment by zeronsama** [comment]
确实是我网络问题，但是很奇怪，明明有 `except UnknownError:` 但是访问失败会让整台bot都运行不起来
