### ISSUE TITLE
python3.12无法使用

### ISSUE THREAD

**Issue by FurLC** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#36]
操作系统：
> Distributor` ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

服务器日志：
错误日志已补全
>07-31 15:55:49 [ERROR] nonebot | Failed to import "nonebot_plugin_maimaidx"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot_plugin_maimaidx/__init__.py", line 4, in <module>
    from .command import *
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot_plugin_maimaidx/command/__init__.py", line 1, in <module>
    from .mai_alias import *
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot_plugin_maimaidx/command/mai_alias.py", line 20, in <module>
    from ..config import *
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot_plugin_maimaidx/config.py", line 16, in <module>
    maiconfig = get_plugin_config(Config)
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/plugin/__init__.py", line 173, in get_plugin_config
    return type_validate_python(config, model_dump(get_driver().config))
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/nonebot/compat.py", line 212, in type_validate_python
    return TypeAdapter(type_).validate_python(data)
  File "/root/lengchuan-bot/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 256, in validate_python
    return self.validator.validate_python(__object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
maimaidxtoken
  Field required [type=missing, input_value={'driver': '~fastapi+~htt...cm_send_media': 'False'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

如有问题请指出，谢谢

**Comment by Yuri-YuzuChaN** [comment]
更新 pydantic

**Comment by Yuri-YuzuChaN** [comment]
你在 `.env` 添加一个 `MAIMAIDXTOKN=` 再试试，不用填写，可能是 `pydantic` 2.0 不能空字段

**Comment by Yuri-YuzuChaN** [comment]
你的这个日志没发全 `pydantic_core._pydantic_core.ValidationError: 1 validation error for Config` 这后面应该还有内容的

**Comment by Yuri-YuzuChaN** [comment]
`MAIMAIDXTOKEN=`
