### ISSUE TITLE
在载入时遇到问题

### ISSUE THREAD

**Issue by gzx7301** [Yuri-YuzuChaN/nonebot-plugin-maimaidx#42]
```
[root@localhost vstd]# nb run
使用 Python: /root/vstd/.venv/bin/python
09-17 16:58:46 [SUCCESS] nonebot | NoneBot is initializing...
09-17 16:58:46 [INFO] nonebot | Current Env: prod
09-17 16:58:47 [ERROR] nonebot | Failed to import "nonebot_plugin_maimaidx"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot_plugin_maimaidx/__init__.py", line 4, in <module>
    from .command import *
  File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot_plugin_maimaidx/command/__init__.py", line 1, in <module>
    from .mai_alias import *
  File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot_plugin_maimaidx/command/mai_alias.py", line 20, in <module>
    from ..config import *
  File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot_plugin_maimaidx/config.py", line 16, in <module>
    maiconfig = get_plugin_config(Config)
  File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot/plugin/__init__.py", line 173, in get_plugin_config
    return type_validate_python(config, model_dump(get_driver().config))
  File "/root/vstd/.venv/lib/python3.9/site-packages/nonebot/compat.py", line 225, in type_validate_python
    return TypeAdapter(type_).validate_python(data)
  File "/root/vstd/.venv/lib/python3.9/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "/root/vstd/.venv/lib/python3.9/site-packages/pydantic/type_adapter.py", line 366, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
maimaidxtoken
  Field required [type=missing, input_value={'
driver': '~fastapi', 'h...66B27D644ADFDABD6EA423'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```
[pyproject.zip](https://github.com/user-attachments/files/17025612/pyproject.zip)

Python 3.9.18 (main, Aug 23 2024, 00:00:00) 
[GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] on linux
已经使用虚拟环境

**Comment by gzx7301** [comment]
DRIVER=~fastapi
PORT=10220
HOST=0.0.0.0
LOG_LEVEL=INFO
FASTAPI_RELOAD=false
SUPERUSERS=["1省略5"]  # 配置 NoneBot 超级用户
NICKNAME=["chino"]  # 配置机器人的昵称
COMMAND_START=["/", ""]
MAIMAIDXPATH=/root/std/static
STEAM_DISABLE_BROADCAST_ON_STARTUP=true
STEAM_BROADCAST_TYPE=part
STEAM_API_KEY=[此处省略]

**Comment by nuym** [comment]
> .env.prod
> 
> ```
> DRIVER=~fastapi
> PORT=10220
> HOST=0.0.0.0
> LOG_LEVEL=INFO
> FASTAPI_RELOAD=false
> SUPERUSERS=["1省略5"]  # 配置 NoneBot 超级用户
> NICKNAME=["chino"]  # 配置机器人的昵称
> COMMAND_START=["/", ""]
> MAIMAIDXPATH=/root/std/static
> STEAM_DISABLE_BROADCAST_ON_STARTUP=true
> STEAM_BROADCAST_TYPE=part
> STEAM_API_KEY=[此处省略]
> ```

根据报错来看，配置文件没有完成
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
maimaidxtoken
  Field required [type=missing, input_value={'
driver': '~fastapi', 'h...66B27D644ADFDABD6EA423'}, input_type=dict]
```

**Comment by Yuri-YuzuChaN** [comment]
没有token也需要配置 `MAIMAIDXTOKEN=`，直接留空

**Comment by gzx7301** [comment]
我尝试添加该设置项 他现在正常了 谢谢！
